version: '3.4'
name: market-basket-analysis

services:
  envoy:
    image: envoyproxy/envoy:distroless-v1.32.3
    container_name: envoy
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./envoy:/etc/envoy
    depends_on:
      create-envoy-config-file:
        condition: service_completed_successfully
      api:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 128M

  create-envoy-config-file:
    build:
      context: .
      dockerfile: envoy/Dockerfile.create-config-file
    container_name: create-envoy-config-file
    entrypoint: sh -c
      "envsubst < /etc/envoy/envoy.template.yaml > /etc/envoy/envoy.yaml &&
       exit 0"
    environment:
      JWKS_HOST: ${JWKS_HOST}
      JWKS_URI: ${JWKS_URI}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
    volumes:
      - ./envoy:/etc/envoy

  api:
    image: kronmag/market-basket-analysis-api
    container_name: api
    volumes:
      - api-data:/app/data
    restart: on-failure
    healthcheck:
      test: [ "CMD", "/bin/grpc_health_probe", "-addr=:8080" ]
      timeout: 10s
      interval: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M

volumes:
  api-data: