version: '3.4'

services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    build:
      context: ../.
      dockerfile: MarketBasketAnalysis.Server.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  grpc-ui:
    image: fullstorydev/grpcui:v1.4.2
    command: -plaintext api:8080
    restart: on-failure
    ports:
      - 8082:8080
    depends_on:
      api:
        condition: service_started