//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketBasketAnalysis.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarketBasketAnalysis.Infrastructure.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read association rules from file &quot;{0}&quot;. See the inner exception for details..
        /// </summary>
        internal static string AssociationRuleCsvHelper_FailedToReadRulesFromFile {
            get {
                return ResourceManager.GetString("AssociationRuleCsvHelper.FailedToReadRulesFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write association rules to file &quot;{0}&quot;. See the innter exeption for details..
        /// </summary>
        internal static string AssociationRuleCsvHelper_FailedToWriteRulesToFile {
            get {
                return ResourceManager.GetString("AssociationRuleCsvHelper.FailedToWriteRulesToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add mining settings profile: the profile with the name &quot;{0}&quot; already exists in the database..
        /// </summary>
        internal static string MiningSettingsProfileRepository_FailedToAddProfile {
            get {
                return ResourceManager.GetString("MiningSettingsProfileRepository.FailedToAddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove mining settings profile: the profile with the name &quot;{0}&quot; doesn&apos;t exist in the database..
        /// </summary>
        internal static string MiningSettingsProfileRepository_FailedToRemoveProfile {
            get {
                return ResourceManager.GetString("MiningSettingsProfileRepository.FailedToRemoveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database operation failed due to an error. See the inner exception for details..
        /// </summary>
        internal static string MiningSettingsProfileRepository_OperationFailed {
            get {
                return ResourceManager.GetString("MiningSettingsProfileRepository.OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile with the name &quot;{0}&quot; not found in the database..
        /// </summary>
        internal static string MiningSettingsProfileRepository_ProfileNotFound {
            get {
                return ResourceManager.GetString("MiningSettingsProfileRepository.ProfileNotFound", resourceCulture);
            }
        }
    }
}
