// <auto-generated />
using MarketBasketAnalysis.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketBasketAnalysis.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("MarketBasketAnalysis.Infrastructure.DataTransferObject.ItemConversionRuleDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MiningProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("Item", "Group");

                    b.HasIndex("MiningProfileId");

                    b.ToTable("ItemConversionRules");
                });

            modelBuilder.Entity("MarketBasketAnalysis.Infrastructure.DataTransferObject.ItemExclusionRuleDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExactMatch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreCase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MiningProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("ItemPattern", "ExactMatch", "IgnoreCase");

                    b.HasIndex("MiningProfileId");

                    b.ToTable("ItemExclusionRules");
                });

            modelBuilder.Entity("MarketBasketAnalysis.Infrastructure.DataTransferObject.MiningSettingsProfileDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("MinConfidence")
                        .HasColumnType("REAL");

                    b.Property<double>("MinSupport")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MiningSettingsProfiles");
                });

            modelBuilder.Entity("MarketBasketAnalysis.Infrastructure.DataTransferObject.ItemConversionRuleDTO", b =>
                {
                    b.HasOne("MarketBasketAnalysis.Infrastructure.DataTransferObject.MiningSettingsProfileDTO", "MiningProfile")
                        .WithMany("ItemConversionRules")
                        .HasForeignKey("MiningProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiningProfile");
                });

            modelBuilder.Entity("MarketBasketAnalysis.Infrastructure.DataTransferObject.ItemExclusionRuleDTO", b =>
                {
                    b.HasOne("MarketBasketAnalysis.Infrastructure.DataTransferObject.MiningSettingsProfileDTO", "MiningProfile")
                        .WithMany("ItemExclusionRules")
                        .HasForeignKey("MiningProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiningProfile");
                });

            modelBuilder.Entity("MarketBasketAnalysis.Infrastructure.DataTransferObject.MiningSettingsProfileDTO", b =>
                {
                    b.Navigation("ItemConversionRules");

                    b.Navigation("ItemExclusionRules");
                });
#pragma warning restore 612, 618
        }
    }
}
